version: "3.8"
services:
  gifu-ui:
    build: .
    container_name: gifu-ui
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - /var/opt/app_data/files/picture:/var/data/files/picture
      - /var/opt/certs:/certs
      - ./:/app